version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: pragas
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    restart: unless-stopped
  web:
    build: .
    command: python deploy.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      FLASK_ENV: development
    depends_on:
      - postgres

volumes:
  pgdata: