name: Deploy to GCP VM

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GCP VM
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
        HOST: ${{ secrets.IP  }}
        USER: gustavo_von
      run: |
        echo "$PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        rsync -avz -e "ssh -i deploy_key -o StrictHostKeyChecking=no" --exclude '.git/' --exclude '.github/' ./ $USER@$HOST:/home/gustavo_von/ControlePragas
        ssh -i deploy_key $USER@$HOST "cd /home/gustavo_von/ControlePragas && git checkout master && git fetch --all && git reset --hard origin/master && git pull && sudo docker-compose up -d --build"
        rm -f deploy_key